config/routes.rb
Example::Application.routes.draw do
  get "platforms/ios"
  get "platforms/android"

  root 'games#show_all'
  resources :games
  match '/english', to: 'languages#english', via: 'get'
  match '/german', to: 'languages#german', via: 'get'
  match '/ios', to: 'platforms#ios', via: 'get'
  match '/android', to: 'platforms#android', via: 'get'

end

app/models/android_game.rb
class AndroidGame < ActiveRecord::Base
end

app/models/game_details.rb
class GameDetails < ActiveRecord::Base
	belongs_to :games
end

app/models/games.rb
class Games < ActiveRecord::Base
	has_many :game_details

	def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
		  find(:all)
		end
	end

end

app/models/ios_game.rb
class IosGame < ActiveRecord::Base
end

app/models/tenant_games.rb
class TenantGames < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_language #used to ensure that new sessions don't need to click on a language to avoid 
		# raising an exception
		if session[:language].nil?
		   session[:language] = 1
		end
	end

	def current_platform #used to ensure that new sessions don't need to click on a platform to avoid 
		# raising an exception
		if session[:platform_type].nil?
			session[:platform_type] = IosGame
		end
	end

	def cleanup(games)
		games.each do |game| 
			game_details = GameDetails.find_by(game_id: game.id, language_id: 1)
			if game_details.nil? #some games seem to have empty game_details, this removes them before the next block,
				#and avoids raising an exception
				games.delete(game)
			else 
				if game_details.review.blank?
					games.delete(game)
				end
			end
		end
	end

	def make_link(game)
		if game.type == "IosGame"
			link = "https://itunes.apple.com/app/id#{game.store_application_id}"
		else
			link = "https://play.google.com/store/apps/details?id=#{game.store_application_id}"
		end
	link
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :current_language
	before_action :current_platform

	def show_all
		games = Games.order(id: :desc).where(type: session[:platform_type])
		cleanup(games)
		@games = games.paginate(page: params[:page])
	end

	def show
		@game = Games.find_by(id:params[:id])
		@rating = @game.hitfox_rating_id
		@game_detail = GameDetails.find_by(game_id: @game.id, language_id: session[:language])
		@link = make_link(@game)
	end

	def index
		@results = Games.where(type: session[:platform_type]).search(params[:search])
	end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
	def english
		session[:language]=1
		redirect_to(:back) #will need to change this to redirect to current page
	end

	def german
		session[:language]=6
		redirect_to(:back)
	end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController

  def ios
  	session[:platform_type]=IosGame
  	redirect_to root_url
  end

  def android
  	session[:platform_type]=AndroidGame
  	redirect_to root_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/game_details_helper.rb
module GameDetailsHelper
end

app/helpers/games_helper.rb
module GamesHelper


end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/game_details/show.html.erb
Title first:

</br><%= @game.title %>

<p> then the description: </p>
<p> <%= @game.review %> </p>

<p> then the pros and cons: </p>
<p> Pros: </p>
<p> <%= @game.review_pros %>
</p>
<p> Cons: </p>
<p> <%= @game.review_cons %>
	</p>

app/views/game_details/show_all.html.erb
Lots and lots of games:

<ul>

<% @firstgame.each do |game| %>

	<li> <%= game.title %>
		<%= link_to('See game details', game) %>
	</li>
	<% end %>

</ul>

app/views/games/index.html.erb
<div class="container results-list">
	<% @results.each do |game| %>
	<ul>
		<li> <%= game.name %>
		<%= link_to 'See game details', game_path(game) %>
		</li>
	</ul>
	<% end %>
</div>

app/views/games/show.html.erb
<div class='carousel container-fluid'>
	<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
	<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
	  <div class="carousel-inner">
	    <div class="item active"><!-- class of active since it's the first item -->
	      <%= image_tag('screenshot2.jpeg', alt:'first screen')%>
	    </div>
	    <div class="item">
	      <%= image_tag('screenshot3.jpeg', alt:'first screen')%>
	    </div>
	    <div class="item">
	      <%= image_tag('screenshot4.jpeg', alt:'first screen')%>
	    </div>
	  </div><!-- /.carousel-inner -->
	  <!--  Next and Previous controls below
	        href values must reference the id for this carousel -->
	    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
	    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
	</div><!-- /.carousel -->
<div class="description container-fluid">
	<h1><%= @game_detail.title %></h1>
	<div class="row"><%(4 - @rating).times do %>
		<%= image_tag('star.png', class:"rating") %>
		<% end %>
	</div>
	<p><%= @game_detail.review %></p>
	<hr>
	<div class="row">
		<div class="pros-and-cons">
			<%= image_tag('plus.png', alt:'plus', class:"fucker") %>
			<% @game_detail.review_pros.split('","').each do |pro| %>
			<ul>
				<li><%= pro.delete('""[]') %></li>
			</ul>
			<% end %>
		</div>
	</div>
<hr>
	<div class="row">
		<div class="pros-and-cons">
			<%= image_tag('minus.png', alt:'minus', class:"fucker") %>
		</br>
			<ul>
			<% @game_detail.review_cons.split('","').each do |con| %>
				<li><%= con.delete('""[]') %></li>
			<% end %>
			</ul>
		</div>
	</div>
	<hr>	
	<div class="row">
		<%= link_to "Download now!", @link, class: "btn btn-large btn-primary download-button" %>
	</div>


</div>
</div>

app/views/games/show_all.html.erb
<div class="container games-list">
<%= will_paginate %>
	<% @games.each do |game| %>
	<ul>
		<li> <%= game.name %>
		<%= link_to 'See game details', game_path(game) %>
		</li>
		<li> Game Finder Rating: <%= game.hitfox_rating_id %></li>
	</ul>
	<% end %>
<%= will_paginate %>
</div>

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <small>
    Game Finder by ... Applift?
  </small>
  <nav>
    <ul>
      <li> <%= link_to "About", '#' %></li>
      <li> <%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default header navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Game Finder", root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= form_tag games_path, method: 'get', class:"navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class:"form-control", placeholder:"Search" %>
          <%= submit_tag "Search", class:"btn btn-large btn-primary" %>
        </div>
        <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'iOS Games', ios_path %></li>
        <li><%= link_to 'Android Games', android_path %></li>
        <li><%= link_to image_tag('england.png'), english_path %></li>
        <li><%= link_to image_tag('de.png'), german_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= render 'layouts/shim' %>
</head>
<body>

	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/platforms/android.html.erb
<h1>Platforms#android</h1>
<p>Find me in app/views/platforms/android.html.erb</p>

app/views/platforms/ios.html.erb
<h1>Platforms#ios</h1>
<p>Find me in app/views/platforms/ios.html.erb</p>